name: docker buildx

on:
  workflow_dispatch:
    inputs:
      debian-ver:
        type: string
        description: Debian Version
        default: bookworm
      qt-ver-major:
        type: string
        description: Qt Version Major
        default: "6"
      qt-ver-minor:
        type: string
        description: Qt Version Minor
        default: "5"
      qt-ver-patch:
        type: string
        description: Qt Version Patch
        default: "3"

# on:
#   push:
#     branches:
#       - 'main'

jobs:
  build:
    name: Docker build
    runs-on: self-hosted
    timeout-minutes: 1440
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            DEBIAN_VER=${{ github.event.inputs.debian-ver }}
            QT_VER_MAJOR=${{ github.event.inputs.qt-ver-major }}
            QT_VER_MINOR=${{ github.event.inputs.qt-ver-minor }}
            QT_VER_PATCH=${{ github.event.inputs.qt-ver-patch }}
          platforms: linux/amd64
          push: true
          tags: mb1986/debian-qt-arm32v7:bookworm-qt6.5.3
          cache-from: type=registry,ref=mb1986/debian-qt-arm32v7:buildcache
          cache-to: type=registry,ref=mb1986/debian-qt-arm32v7:buildcache,mode=max